{
 "title": "RGGR Application Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  { "title": "Cache Metrics - ${job}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "job" },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rggr_cache_total{type=\"hits\", job=\"$job\"})\n  /\n  (\n    sum(rggr_cache_total{type=\"hits\", job=\"$job\"})\n    +\n    sum(rggr_cache_total{type=\"misses\", job=\"$job\"})\n  )\n)\n",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Authors Cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_cache_total{type=\"authors_total\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Authors"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_cache_total{type=\"hits\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Books Cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_cache_total{type=\"books_total\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Books"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_cache_total{type=\"misses\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Works Cached",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_cache_total{type=\"works_total\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Authors"
    }
   ]
  },
  { "title": "Controller Metrics - ${job}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "job" },
  {
   "title": "ETag Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rggr_controller_etag_total{type=\"matches\", job=\"$job\"})\n  /\n  (\n    sum(rggr_controller_etag_total{type=\"matches\", job=\"$job\"})\n    +\n    sum(rggr_controller_etag_total{type=\"mismatches\", job=\"$job\"})\n  )\n)",
     "legendFormat": "Mismatches"
    }
   ]
  },
  {
   "title": "Denorm Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_controller_waiting_operations{type=\"denorm_waiting\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "Refresh Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_controller_waiting_operations{type=\"refresh_waiting\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "GQL Batches Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_gqlclient_total{type=\"batches_sent\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "GQL Queries Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_gqlclient_total{type=\"queries_sent\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "ETag Matches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_controller_etag_total{type=\"matches\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Matches"
    }
   ]
  },
  {
   "title": "Denorm Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_controller_total_operations{type=\"denorm_completed\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "Refresh Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_controller_total_operations{type=\"refresh_completed\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "GQL Batches Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_gqlclient_total{type=\"batches_sent\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "GQL Queries Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_gqlclient_total{type=\"queries_sent\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "ETag Mismatches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rggr_controller_etag_total{type=\"mismatches\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Mismatches"
    }
   ]
  },
  {
   "title": "Denorm Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_controller_total_operations{type=\"denorm_completed\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  {
   "title": "Refresh Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rggr_controller_total_operations{type=\"refresh_completed\", job=\"$job\"}",
     "legendFormat": "Denorm"
    }
   ]
  },
  { "title": "Http Performance - ${job}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "job" },
  {
   "title": "HTTP Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rggr_http_request_duration_seconds_bucket{job=\"$job\"}[5m])) by (le, method, path, status))",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rggr_http_requests_inflight{job=\"$job\"}",
     "legendFormat": "Inflight"
    }
   ]
  },
  {
   "title": "HTTP Total Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(rggr_http_total_requests{job=\"$job\"}[1m])) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  }
 ]
}