{
 "title": "rreading-glasses",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rg_cache_total,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pending Refreshes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_controller_pending_operations{type=\"refresh\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_db_total{namespace=\"$namespace\", type=\"authors\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Works",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_db_total{type=\"works\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Editions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_db_total{type=\"editions\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_db_total{type=\"series\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASINs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_db_total{type=\"asins\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Denormalizations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_controller_pending_operations{type=\"denormalization\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rg_cache_total{type=\"hits\", namespace=\"$namespace\"})\n  /\n  (\n    sum(rg_cache_total{type=\"hits\", namespace=\"$namespace\"})\n    +\n    sum(rg_cache_total{type=\"misses\", namespace=\"$namespace\"})\n  )\n)\n",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Avg. Upstream QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(rg_gql_total{namespace=\"$namespace\", type=\"queries_sent\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rg_http_inflight{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No-op Refreshes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rg_controller_total_operations{type=\"etag_matches\", namespace=\"$namespace\"})\n  /\n  (\n    sum(rg_controller_total_operations{type=\"etag_matches\", namespace=\"$namespace\"})\n    +\n    sum(rg_controller_total_operations{type=\"etag_mismatches\", namespace=\"$namespace\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare Busts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(rg_cloudflare_total{namespace=\"$namespace\", type=\"urls_busted\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(rg_process_cpu_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum by (job) (rg_process_resident_memory_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(rg_process_network_transmit_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum by (job) (rate(rg_process_network_receive_bytes_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (increase(rg_http_requests_bucket{namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(rg_http_requests_count{namespace=\"$namespace\"}[1m])) by (path)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Codes per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(rg_http_requests_count{namespace=\"$namespace\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Scheduler Pauses",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "increase(go_sched_latencies_seconds_bucket{namespace=\"$namespace\", container=\"$namespace\"}[$__interval])",
     "legendFormat": "Scheduler"
    }
   ]
  }
 ]
}